name: Deploy VitePress site to gh-pages

on:
  push:
    branches: [master] # 根据实际情况调整为你的默认分支
  workflow_dispatch:

permissions:
  contents: read
  packages: read # 如果使用了包缓存
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn' # 或者'yarn'，根据你的实际使用情况

      - name: Install Dependencies
        run: yarn install # 或者'pnpm i'，'yarn'

      - name: Build with VitePress
        run: yarn run docs:build # 或者'pnpm run docs:build'，'yarn build'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
      #    cname: your-custom-domain.com # 如果有自定义域名，取消注释并填写
      #    branch: gh-pages # 指定部署的目标分支  
